title: Monique Mizzi - Numerical Analysis # your name (or website title) here
logo: https://github.com/mmiz02/eportfolio/blob/master/images/1.jpg # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  First description 
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/example/">Click here to access nothing</a> 
  
remote_theme: jekyll/minima

google_analytics: UA-000000-0 # your Google Analytics tracking ID here


