title: Monique Mizzi # your name (or website title) here
logo: "/images/mm.png" # your photo (or logo) here

  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
