title: Monique Mizzi # your name (or website title) here
logo: "/images/mm.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Detail-oriented professional, currently working as a Radiation Protection Regulator with the Radiation Protection Commission in Malta. Pursuing a Master's in Data Science with the University of Essex, I'm passionate about deriving insights from data and hope to be able to apply it to guide future regulatory decisions to improve public and environmental safety.
  <br><br>
  This portfolio showcases a selection of tasks and projects from this module along with a Reflective essay, outlining my learning journey and key takeaways. 
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
